version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-email-services-app
    container_name: my-email-services-app 
    command: php artisan serve --host=0.0.0.0 --port=9099
    volumes:
      - .:/var/www/html
    ports:
      - "9099:9099"
    depends_on:
      - db


  db:
    image: mysql:latest
    container_name: my-email-db-container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: emailservice
      MYSQL_PASSWORD: password
    ports:
      - "3301:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
